### ISSUE TITLE
Add error handling for subdomain registrar failures

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#46] opened 2020-02-14 15:15 UTC
Per https://github.com/blockstack/app/issues/97#issuecomment-585250016

**Comment by jasperjansz** [comment] 2020-02-18 10:09
We can have a generic message for now: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=6847%3A964

In next releases we can have a more specific message depending on the type of error, or automatically try registering it again without user action

**Comment by hstove** [comment] 2020-02-18 20:00
Closing, duplicate of https://github.com/blockstack/app/issues/192

**Closed by hstove** 2020-02-18 20:00 UTC
Labels: enhancement
